/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IMerkleAirdropFactory,
  IMerkleAirdropFactoryInterface,
} from "../IMerkleAirdropFactory";

const _abi = [
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IMerkleAirdropFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IMerkleAirdropFactoryInterface {
    return new utils.Interface(_abi) as IMerkleAirdropFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMerkleAirdropFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IMerkleAirdropFactory;
  }
}
