/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IMerkleAirdrop,
  IMerkleAirdropInterface,
} from "../IMerkleAirdrop";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_startTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_endTime",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "_merkleRoot",
        type: "bytes32",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IMerkleAirdrop__factory {
  static readonly abi = _abi;
  static createInterface(): IMerkleAirdropInterface {
    return new utils.Interface(_abi) as IMerkleAirdropInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMerkleAirdrop {
    return new Contract(address, _abi, signerOrProvider) as IMerkleAirdrop;
  }
}
