/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IVotingEligibility,
  IVotingEligibilityInterface,
} from "../IVotingEligibility";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
    ],
    name: "isEligible",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IVotingEligibility__factory {
  static readonly abi = _abi;
  static createInterface(): IVotingEligibilityInterface {
    return new utils.Interface(_abi) as IVotingEligibilityInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVotingEligibility {
    return new Contract(address, _abi, signerOrProvider) as IVotingEligibility;
  }
}
