/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IVoteEscrow",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVoteEscrow__factory>;
    getContractFactory(
      name: "IVotingEligibility",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVotingEligibility__factory>;
    getContractFactory(
      name: "IMerkleAirdropFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMerkleAirdropFactory__factory>;
    getContractFactory(
      name: "IMerkleDistributor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMerkleDistributor__factory>;
    getContractFactory(
      name: "MerkleAirdrop",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MerkleAirdrop__factory>;
    getContractFactory(
      name: "IMerkleAirdrop",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMerkleAirdrop__factory>;
    getContractFactory(
      name: "MerkleAirdropFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MerkleAirdropFactory__factory>;
    getContractFactory(
      name: "MockCve",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCve__factory>;
    getContractFactory(
      name: "SnapshotVotingStrategy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SnapshotVotingStrategy__factory>;
    getContractFactory(
      name: "VotingEligibility",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VotingEligibility__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IVoteEscrow",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IVoteEscrow>;
    getContractAt(
      name: "IVotingEligibility",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IVotingEligibility>;
    getContractAt(
      name: "IMerkleAirdropFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMerkleAirdropFactory>;
    getContractAt(
      name: "IMerkleDistributor",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMerkleDistributor>;
    getContractAt(
      name: "MerkleAirdrop",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MerkleAirdrop>;
    getContractAt(
      name: "IMerkleAirdrop",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMerkleAirdrop>;
    getContractAt(
      name: "MerkleAirdropFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MerkleAirdropFactory>;
    getContractAt(
      name: "MockCve",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCve>;
    getContractAt(
      name: "SnapshotVotingStrategy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SnapshotVotingStrategy>;
    getContractAt(
      name: "VotingEligibility",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.VotingEligibility>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
