name: Forge test
on:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Yarn dependencies
        run: yarn install --immutable || true

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Forge dependencies
        run: forge install
      - name: Run test harness (with automatic retry after delay)
        shell: bash
        run: |
          set +e
      
          echo "Running forge tests..."
          forge test --ffi
          EXIT_CODE=$?
      
          if [ $EXIT_CODE -ne 0 ]; then
            echo
            echo "Some tests failed."
            echo
            echo "Waiting 3 minutes before retrying failed tests..."
            echo
            sleep 60
      
            echo "Re-running failed tests..."
            forge test --rerun --ffi
            EXIT_CODE=$?
          fi
      
          exit $EXIT_CODE
        env:
          ETH_NODE_URI_MAINNET: ${{ secrets.ETH_NODE_URI_MAINNET }}
          ETH_NODE_URI_ARBITRUM: ${{ secrets.ETH_NODE_URI_ARBITRUM }}
          ETH_NODE_URI_OPTIMISM: ${{ secrets.ETH_NODE_URI_OPTIMISM }}
          ETH_NODE_URI_BASE: ${{ secrets.ETH_NODE_URI_BASE }}
          MON_NODE_URI_MONAD_MAINNET: ${{ secrets.MON_NODE_URI_MONAD_MAINNET }}
